root = "."
tmp_dir = "tmp"

[build]
# Path to your main.go file
cmd = "go build -o ./tmp/main ./cmd/server"
# Binary file generated
bin = "tmp/main"
# Directory to watch for changes
include_dir = ["cmd", "internal", "pkg"]
# File extensions to watch
include_ext = ["go", "tpl", "tmpl", "html"]
# Files to exclude
exclude_dir = ["assets", "tmp", "vendor"]
# Additional arguments when running the binary
args_bin = []
# Delay before restarting after a change (ms)
delay = 1000

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[log]
time = true

[misc]
clean_on_exit = true
