version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: algolearn_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - algolearn-net

volumes:
  db-data: {}
  
networks:
  algolearn-net: {}



