name: algolearn
services:
  db:
    image: postgres:latest
    container_name: algolearn_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA_DEVICE}/${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - algolearn-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 0s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algolearn_app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - algolearn-net
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ${POSTGRES_DATA_DEVICE}
      o: bind

networks:
  algolearn-net: {}
