version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: algolearn_postgres
    environment:
        POSTGRES_USER: algoadmin 
        POSTGRES_PASSWORD: algolearn4stml 
        POSTGRES_DB: algolearn 
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - algolearn-net

volumes:
  db-data: {}
  
networks:
  algolearn-net: {}



