const tintColorLight = "#333";
const tintColorDark = "#333";

export default {
  light: {
    text: "#000",
    background: "#FFFFFF",
    tint: tintColorLight,
    tabIconDefault: "#1E1E1E",
    tabIconSelected: tintColorLight,
    tabIconHomeSelected: "#FCC931",
    tabIconInboxSelected: "#9F52C5",
    tabIconExploreSelected: "#25A879",
    tabIconChallengesSelected: "#1CC0CB",
    buttonText: "#fff",
    buttonBackground: "#1E1E1E",
    border: "#333",
    placeholderText: "#999",
    icon: "#333",
    dangerBgColor: "#FF0000",
    successBgColor: "#28a745",
    warningBgColor: "#ffc107",
    infoBgColor: "#17a2b8",
    dangerTextColor: "#fff",
    successTextColor: "#fff",
    warningTextColor: "#000",
    infoTextColor: "#fff",
    linkColor: "#1E90FF",
    hoverColor: "#555",
    activeColor: "#0000FF",
    disabledColor: "#D3D3D3",
    errorColor: "#DC3545",
    alertColor: "#FFC107",
  },
  dark: {
    text: "#fff",
    background: "#121212",
    tint: tintColorDark,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorDark,
    tabIconHomeDefault: "#1E1E1E",
    tabIconHomeSelected: "#FCC931",
    tabIconInboxSelected: "#9F52C5",
    tabIconExploreSelected: "#25A879",
    tabIconChallengesSelected: "#1CC0CB",
    buttonText: "#000",
    buttonBackground: "white",
    border: "#888",
    placeholderText: "#666",
    icon: "#fff",
    dangerBgColor: "#FF0000",
    successBgColor: "#28a745",
    warningBgColor: "#ffc107",
    infoBgColor: "#17a2b8",
    dangerTextColor: "#fff",
    successTextColor: "#fff",
    warningTextColor: "#000",
    infoTextColor: "#fff",
    linkColor: "#1E90FF",
    hoverColor: "#AAA",
    activeColor: "#0000FF",
    disabledColor: "#555",
    errorColor: "#DC3545",
    alertColor: "#FFC107",
  },
};
